import React from 'react';
import { useInterview } from '../context/InterviewContext';
import { Award, CheckCircle2, TrendingUp, Download, ArrowLeft, ShieldCheck, Sparkles } from 'lucide-react';

export default function ScorecardView({ onBackToDashboard }) {
  const { finalReport, activeSession } = useInterview();

  const report = finalReport || {
    roleTitle: activeSession?.roleTitle || 'Senior Software Engineer',
    overallScore: 82,
    recommendation: 'Strong Hire',
    executiveSummary: 'Candidate demonstrated solid reasoning calibrated for the target seniority level, communicating tradeoffs clearly and responding to deep-dive follow-ups systematically.',
    metrics: {
      technicalDepth: 84,
      problemSolving: 85,
      communication: 82,
      composure: 88,
      focalAttention: 94,
      stressIndex: 26
    },
    keyStrengths: [
      'Articulated distributed caching and concurrency locking mechanisms clearly.',
      'Structured problem breakdown with attention to fault tolerance.',
      'High composure and clear technical delivery throughout the session.'
    ],
    areasForGrowth: [
      'Can quantify latency bottlenecks and network throughput limits more explicitly.',
      'Deepen explanations of automated rollback strategies during continuous deployment.'
    ],
    questionBreakdown: [
      {
        questionNumber: 1,
        candidateAnswer: 'I would implement a Redis caching layer with cache-aside pattern and distributed locking.',
        score: 84,
        feedback: 'Good grasp of architectural patterns with clear communication.'
      }
    ]
  };

  const handleExportTxt = () => {
    const content = `========================================================================
             VIVORA AI - EXECUTIVE CANDIDATE SCORECARD
========================================================================
Role: ${report.roleTitle || 'Software Engineer'}
Overall Score: ${report.overallScore || 80}%
Verdict: ${report.recommendation || 'Hire'}
Date: ${new Date().toLocaleString()}

------------------------------------------------------------------------
EXECUTIVE SUMMARY:
------------------------------------------------------------------------
${report.executiveSummary || 'Telemetry evaluation completed.'}

------------------------------------------------------------------------
EVALUATION METRIC BREAKDOWN:
------------------------------------------------------------------------
• Technical Depth:     ${report.metrics?.technicalDepth || 80}%
• Problem Solving:     ${report.metrics?.problemSolving || 80}%
• Communication:       ${report.metrics?.communication || 80}%
• Composure & Focus:   ${report.metrics?.composure || 85}%

------------------------------------------------------------------------
KEY STRENGTHS:
------------------------------------------------------------------------
${(report.keyStrengths || []).map(s => `• ${s}`).join('\n')}

------------------------------------------------------------------------
AREAS FOR GROWTH:
------------------------------------------------------------------------
${(report.areasForGrowth || []).map(g => `• ${g}`).join('\n')}

------------------------------------------------------------------------
QUESTION BREAKDOWN:
------------------------------------------------------------------------
${(report.questionBreakdown || []).map((q, idx) => `
[Question #${q.questionNumber || idx + 1}] - Score: ${q.score}%
Answer: "${q.candidateAnswer}"
Critique: ${q.feedback}
`).join('\n')}
========================================================================
                GENERATED BY VIVORA AI ASSESSMENT PORTAL
========================================================================`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Vivora_Scorecard_${report.roleTitle?.replace(/\s+/g, '_') || 'Assessment'}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-in fade-in duration-300">
      
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-indigo-900 via-indigo-800 to-slate-900 text-white rounded-3xl p-6 md:p-8 shadow-xl relative overflow-hidden">
        <div className="relative z-10 flex flex-wrap items-center justify-between gap-4">
          <div className="space-y-2 max-w-xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/10 backdrop-blur-md rounded-full text-xs font-bold text-indigo-200">
              <Award size={14} className="text-amber-400" />
              <span>Assessment Completed</span>
            </div>
            <h2 className="text-2xl md:text-3xl font-black tracking-tight">
              {report.roleTitle || 'Candidate'} Scorecard
            </h2>
            <p className="text-xs md:text-sm text-slate-300 font-medium leading-relaxed">
              {report.executiveSummary}
            </p>
          </div>

          {/* Overall Score Circle */}
          <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-3xl p-6 text-center min-w-[150px]">
            <span className="block text-[11px] font-bold uppercase tracking-wider text-indigo-200">Overall Score</span>
            <span className="font-mono font-black text-4xl text-white">{report.overallScore}%</span>
            <span className="inline-block mt-2 px-3 py-1 bg-emerald-500 text-white text-xs font-black rounded-full uppercase tracking-wider shadow-sm">
              {report.recommendation || 'Hire'}
            </span>
          </div>
        </div>

        {/* Ambient Glow */}
        <div className="absolute right-0 top-0 w-96 h-96 bg-indigo-500/20 rounded-full blur-3xl pointer-events-none"></div>
      </div>

      {/* 4-Metric Grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: 'Technical Depth', score: report.metrics?.technicalDepth || 80, color: 'text-indigo-600 dark:text-indigo-400' },
          { label: 'Problem Solving', score: report.metrics?.problemSolving || 80, color: 'text-emerald-600 dark:text-emerald-400' },
          { label: 'Communication', score: report.metrics?.communication || 80, color: 'text-purple-600 dark:text-purple-400' },
          { label: 'Composure', score: report.metrics?.composure || 85, color: 'text-amber-600 dark:text-amber-400' },
        ].map((item, idx) => (
          <div key={idx} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 text-center shadow-sm">
            <span className="block text-xs font-bold text-slate-400 uppercase tracking-wider">{item.label}</span>
            <span className={`font-mono font-black text-3xl ${item.color} mt-1 block`}>{item.score}%</span>
            <div className="w-full bg-slate-100 dark:bg-slate-800 rounded-full h-1.5 mt-3 overflow-hidden">
              <div className="bg-indigo-600 h-1.5 rounded-full" style={{ width: `${item.score}%` }} />
            </div>
          </div>
        ))}
      </div>

      {/* Strengths & Growth Columns */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        
        {/* Key Strengths */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 space-y-4 shadow-sm">
          <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 font-bold text-sm">
            <CheckCircle2 size={18} />
            <span>Validated Core Strengths</span>
          </div>
          <ul className="space-y-2 text-xs font-medium text-slate-700 dark:text-slate-300 leading-relaxed">
            {(report.keyStrengths || []).map((s, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-emerald-500 font-bold">•</span>
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Growth Areas */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 space-y-4 shadow-sm">
          <div className="flex items-center gap-2 text-amber-600 dark:text-amber-400 font-bold text-sm">
            <TrendingUp size={18} />
            <span>Targeted Areas for Growth</span>
          </div>
          <ul className="space-y-2 text-xs font-medium text-slate-700 dark:text-slate-300 leading-relaxed">
            {(report.areasForGrowth || []).map((g, idx) => (
              <li key={idx} className="flex items-start gap-2">
                <span className="text-amber-500 font-bold">•</span>
                <span>{g}</span>
              </li>
            ))}
          </ul>
        </div>

      </div>

      {/* Question Breakdown List */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 space-y-4 shadow-sm">
        <h3 className="font-black text-base text-slate-900 dark:text-white">
          Dialogue & Response Breakdown
        </h3>

        <div className="space-y-3">
          {(report.questionBreakdown || []).map((q, idx) => (
            <div key={idx} className="p-4 bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 rounded-xl space-y-2">
              <div className="flex justify-between items-center">
                <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400">
                  Response #{q.questionNumber || idx + 1}
                </span>
                <span className="px-2.5 py-0.5 bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 font-bold text-xs rounded-md">
                  Score: {q.score}%
                </span>
              </div>
              <p className="text-xs text-slate-600 dark:text-slate-300 italic">
                "{q.candidateAnswer}"
              </p>
              <div className="text-xs text-slate-700 dark:text-slate-200 font-semibold pt-1 border-t border-slate-200 dark:border-slate-700">
                💡 <strong>Interviewer Critique:</strong> {q.feedback}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Action Footer */}
      <div className="flex flex-wrap items-center justify-between gap-4 pt-2">
        <button
          onClick={onBackToDashboard}
          className="flex items-center gap-2 px-5 py-3 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-xl font-bold text-xs text-slate-700 dark:text-slate-200 transition-all shadow-sm"
        >
          <ArrowLeft size={16} />
          <span>Return to Dashboard</span>
        </button>

        <button
          onClick={handleExportTxt}
          className="flex items-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-bold text-xs md:text-sm transition-all shadow-md shadow-indigo-500/20"
        >
          <Download size={16} />
          <span>Download Telemetry Report (.txt)</span>
        </button>
      </div>

    </div>
  );
}
